### ISSUE TITLE
Display WorkflowExecution stats on Workflow listing page

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#144]
See https://projects.invisionapp.com/d/main#/console/19217882/405979089/preview

**Comment by Vafilor** [comment]
@rushtehrani Are these stats supposed to be live?

Also, are any of these stats going to be stored in database, or do we need to do a query each time?

**Comment by rushtehrani** [comment]
@Vafilor 
> Are these stats supposed to be live?
No, but maybe we can poll for stats every so often.

> Also, are any of these stats going to be stored in database, or do we need to do a query each time?
I think we need to cache/store them but deferring to the implementer to make that decision after research.

**Comment by Vafilor** [comment]
@rushtehrani 

Polling sounds good.

Regarding cache/store, another possibility is to store the data on the workflow template itself as a label.

Might be more efficient to just get it from the DB, but just throwing up some ideas if we want to keep more to k8s.

**Comment by rushtehrani** [comment]
> Regarding cache/store, another possibility is to store the data on the workflow template itself as a label.

I didn't think of that, this might be the best way actually. Wonder if it makes sense to use [Annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) instead if we're not querying objects based on this data?

**Comment by Vafilor** [comment]
I think it's better to assume we will query for it, it provides us more capability.
If we really want, we can add it to both places.

In addition to your example, we might want 
- Sort by least/most failed, # executions, etc.

**Comment by aleksandrmelnikov** [comment]
Overview of decided implementation:

**We are using a database for storing information.**
- Generating statistics is easier than querying kubernetes workflow information
- We can store records of workflows that are gone from k8s
-- Argo garbage collection can delete workflows
-- CronWorkflows have a limit for how many error/successful workflows they keep around
- We don't have to worry about concurrency or race conditions with data updates / inserts / queries.
-- If we were to store the information in k8s via annotation or label, these might be issues.

**We will push information to the database instead of polling.**
- Polling requires running a process every so often. So we'd need to set up a cron
- We'd also be relying on the time-frame being small enough to capture any workflow execution

**We will attempt to use argo "exit handlers" to push information.**
- These are going to run after the workflow completes or errors out
- Adding a side-car container would be too granular, we are focusing on workflow outcomes

**Regarding deletion of workflows, either by garbage collection or cron workflow settings:**
We're going to test out an archive functionality, from argo.
- For now, we may just have an endpoint to report how many are archived.
We can iterate on what information to provide to the user regarding the archived pieces.

**Comment by rushtehrani** [comment]
Issues so far:
1. We should be using internal service names for the API call. T
2. When the call completes, the container continues running. On success we should exit with code 0 and on failure a code other than 0.

In reference to issue 1:
- The internal service name is `onepanel-core.onepanel.svc.cluster.local` and the port is `80`. This will be consistently the same in Kubernetes as long as we don't change the service name or namespace.
- We may also have to set a `NetworkPolicy` in `onepanel` to allow access from other namespaces to the `onepanel-core` pod.

**Comment by aleksandrmelnikov** [comment]
Note: Test on Azure
