### ISSUE TITLE
Node pool does not show all machines for existing workspaces

### ISSUE THREAD

**Issue by savan77** [onepanelio/core#407]
The node pool inside existing workspaces does not show all GPU machines. But can be found while creating new workspaces.

![nodepool_2](https://user-images.githubusercontent.com/16082167/87465964-18096500-c5db-11ea-9473-baa536e88f4d.PNG)

**Comment by Vafilor** [comment]
This happens to workspaces while in edit mode because we load the node pool options from the workspace manifest. 
The actual node pool options come from the system config (as they can be changed at runtime). 

We need to change the node pool options to be loaded from the config.

Here is the line in question.

https://github.com/onepanelio/core/blob/master/server/workspace_server.go#L150
