### ISSUE TITLE
 JupyterLab on GKE does not work with GPU

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#791]
**Describe the bug**
 JupyterLab on GKE does not work with GPU because [`LD_LIBRARY_PATH`](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/11.0/ubuntu20.04-x86_64/base/Dockerfile#L26) is missing. It needs to be set to `/usr/local/nvidia/lib:/usr/local/nvidia/lib64`.

**Note** Setting this env var in Workspace Template directly did not work, suggesting that something could be writing over it when the JupyterLab server runs.

**`opctl` version**
```bash
$ opctl version

CLI version: v0.16.0-rc.2
Manifest version: v0.16.0-rc.2
API version: v0.16.0-rc.2
Web UI version: v0.16.0-rc.2
```

**`opctl init` command**
`opctl init --provider gke --artifact-repository-provider s3 --gpu-device-plugins nvidia`

**Kubernetes information**
 - Cloud provider: GKE
 - Kubernetes version: 1.17.13-gke.2001

**Machine information**
- OS: macOS 10.14.6
- Browser: Chrome

**Screenshots**

**Comment by rushtehrani** [comment]
Additional context around this: If you directly exec into the container in K8s, the environment variable is there, so I suspect that something with our JupyterLab launch process overwrites or clears the environment variable. The VSCode template uses the same image layers and doesn't have this issue.

**Comment by Vafilor** [comment]
@rushtehrani 

*Solution:*

Change Command in workspace template to (note the inclusion of `LD_LIBRARY_PATH`):
```
command: ["/bin/bash", "-c", "pip install onepanel-sdk && start.sh LD_LIBARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64  jupyter lab --LabApp.token='' --LabApp.allow_remote_access=True --LabApp.allow_origin=\"*\" --LabApp.disable_check_xsrf=True --LabApp.trust_xheaders=True --LabApp.base_url=/ --LabApp.tornado_settings='{\"headers\":{\"Content-Security-Policy\":\"frame-ancestors * \'self\'\"}}' --notebook-dir='/data' --allow-root  --GatewayClient.env_whitelist='LD_LIBARY_PATH'"]
```

*Explanation*

The command calls the `start.sh` script. This script ends up calling the subsequent command with ` sudo -E`.
The `-E` flag doesn't pass on certain variables like those that start with `LD`. In order to preserve those variables, we can set them after the `start.sh` invokation.

*Additional Info*
https://serverfault.com/questions/371630/how-to-configure-sudoers-to-always-keep-ld-library-path-envrionment-variable/371646#371646
