### ISSUE TITLE
Some volumes are not deleted on Workflow completion

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#805]
Volumes created via volumeClaimTemplates in Workflows are not deleted when a Workflow completes.

**Comment by Vafilor** [comment]
Ways this can happen:

When `ARGO_POD_GC_STRATEGY` is set to `OnWorkflowSuccess` and a workflow fails, it does keep the volume.

Otherwise, I tested this with `OnPodCompletion` (the default) and a failed or successful workflow deleted the volumes.

This might have been related to the `Patch https://10.0.0.1:443/api/v1/namespaces/` issue from earlier. Maybe that specific kind of failure prevented the volumes from being terminated. But that was a system error in general. It might be worth pursuing a kind of cron that checks for bad resources, since it would be external to any failures. 

I'll keep an eye on this one, but if anyone is able to reproduce it, please post below.

**Comment by rushtehrani** [comment]
This looks to be an issue only when we delete clusters and don't delete paused or running Workspaces. Closing for now.
